Add navbar component
cooperativa-tech/minhocovid19 pull request #19
Opened 2020-04-12 22:59 UTC by DavideSilva

2020-04-15 15:54 UTC, DavideSilva commented
The logo size change on scroll is still missing.

Also, the NavLink and NavButton components are copy-pasted from the Link and Button, respectively. The only diferences are related to styling.

And can we try to keep the imports sorted alphabetically? Not a major issue but I think that it helps code readability and also it helps when there are rebasing conflicts.

2020-04-15 15:57 UTC, DavideSilva commented
Oh and also, please go to town reviewing this. I'm not very proficient at this frontend stuff, so please feel free to show me how it should be done 😅

2020-04-16 12:09 UTC, jfranciscosousa requested changes

2020-04-16 12:09 UTC, jfranciscosousa commented on src/components/Navbar/index.js
> +    <header className={styles.root}>
`header` has a different meaning, it's used to specify the header of a section. `h1` and so on do that automatically. No need to use this. The important tag here is `nav` that you already have.

2020-04-16 12:09 UTC, jfranciscosousa commented on src/components/Navbar/index.js
> +        <div className={styles.link}>
Usually, navs go like this `nav > ul > li > a`. Why? It's a pattern used for accessibility. Usually navs are a list of links and users of screen readers are usually expecting lists with links on the navigation part.

Also, every time we have repetition of stuff, `ul` is a good options.

2020-04-16 14:52 UTC, DavideSilva commented on src/components/Navbar/index.js
> +        <div className={styles.link}>
`NavLink` is already an `a`, so I simply switch the `div`s for `li`s and surrounded that with an `ul`

2020-04-16 14:53 UTC, DavideSilva commented on src/components/Navbar/index.js
> +    <header className={styles.root}>
Didn't knew that. Switched for a `div` :+1:

2020-04-16 14:55 UTC, jfranciscosousa approved these changes
Impecable

2020-04-17 14:15 UTC, merged